name: Docker Image CI

on:
  push:
    branches:
      - development
      - main

jobs:
  build_and_publish:
    runs-on:
      - self-hosted
    environment: ${{ github.base_ref == 'main' && 'PRD' || 'DEV' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./API/API.csproj

      - name: Build and publish
        run: dotnet publish ./API/API.csproj -c Release -o ./out /p:UseAppHost=false
        
      - name: Login to Docker Hub
        run: |
          docker login -u ${{ vars.DOCKERHUB_LOGIN }} --password ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ vars.DOCKERHUB_LOGIN }}/${{ github.event.repository.name }}
          tags: |
            type=ref,event=branch
            type=sha,enable=${{ github.ref == 'refs/heads/main' }}
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.publish
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}