name: SonarQube scan check

on:
  pull_request:
    branches:
      - development
      - main

jobs:  
  sonar:
    runs-on:
      - self-hosted
    environment: ${{ github.base_ref == 'main' && 'PRD' || 'DEV' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage

      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Build & Test with Coverage
        run: |
          dotnet build --no-incremental
          dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=${{ vars.SONAR_API_KEY }}
            -Dsonar.projectName=${{ vars.SONAR_API_KEY }}
            -Dsonar.sources=.
            -Dsonar.language=cs
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.coverage.exclusions=**\Program.cs
            -Dsonar.cs.vscoveragexml.reportsPaths="coverage.xml"

      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}